version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/WpfTimelineControl"
      - "/DemoApps/*"
    schedule:
      interval: "weekly"
    target-branch: develop

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Seoul"
