name: Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch all history
      run: |
        git fetch --prune

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        msbuild -verbosity:minimal -t:Build -restore -p:Configuration=Release
