name: Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all history
      run: |
        git fetch --prune

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Debug build
      run: |
        msbuild -verbosity:minimal -t:Rebuild -restore -p:Configuration=Debug

    - name: Unit tests
      run: |
        dotnet test Tests --logger trx --results-directory "TestResults"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Release build
      run: |
        msbuild -verbosity:minimal -t:Rebuild -restore -p:Configuration=Release
