name: Create GitHub Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'DemoApps/**'
      - 'Tests/**'
  workflow_dispatch:

jobs:
  Release-Draft:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all history
      run: |
        git fetch --prune

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.0
      with:
        versionSpec: '5.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.2.0

    - name: GitVersion Outputs
      run: |
        echo '${{ toJSON(steps.gitversion) }}' | jq

    - name: Create GitHub Release
      id: create_release
      uses: release-drafter/release-drafter@v6
      with:
        tag: '${{ steps.gitversion.outputs.nuGetVersionV2 }}'
        name: 'Release ${{ steps.gitversion.outputs.nuGetVersionV2 }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
