name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  Release-Draft:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch all history
      run: |
        git fetch --prune

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1

    - name: GitVersion Outputs
      run: |
        echo '${{ toJSON(steps.gitversion) }}' | jq

    # - name: Create GitHub Release
    #   id: create_release
    #   uses: release-drafter/release-drafter@v6
    #   with:
    #     tag: '${{ steps.gitversion.outputs.semVer }}'
    #     name: 'Release ${{ steps.gitversion.outputs.semVer }}'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
