name: Create GitHub Release

on:
  push:
    branches:
      - main
    paths:
      - 'LICENSE'
      - 'README.md'
      - 'WpfTimeline.sln'
      - '/WpfTimelineControl'
      - '/.github/release-drafter.yml'
      - '/.github/workflows/release-drafter.yml'

permissions:
  contents: read

jobs:
  Release-Draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all history
      run: |
        git fetch --prune

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.2.0
      with:
        versionSpec: '5.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.2.0

    - name: GitVersion Outputs
      run: |
        echo '${{ toJSON(steps.gitversion) }}' | jq

    - name: Create GitHub Release
      id: create_release
      uses: release-drafter/release-drafter@v6
      with:
        tag: '${{ steps.gitversion.outputs.nuGetVersionV2 }}'
        name: 'Release ${{ steps.gitversion.outputs.nuGetVersionV2 }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
